### ISSUE TITLE
node-red crashed with SyntaxError when wio-sensor receives a response like "<"

### ISSUE THREAD

**Issue by mhama** [WarriorRocker/node-red-contrib-wio-seeed#3]
Hi, 
After I've run node-red server for several hours, the server crashed with this call stack, 
![image](https://cloud.githubusercontent.com/assets/618417/16120738/8e1ec826-341b-11e6-95ea-56e0f00298d6.png)

So it crashed here, when parsing something like "<" .
https://github.com/WarriorRocker/node-red-contrib-wio-seeed/blob/master/wio-sensor/wio-sensor.js#L21
I guess that the seeed's server was in bad state at that time and it returns some error page, written in HTML.

So It will be better that the wio-sensor be able to handle non-JSON response string, maybe by adding try ~ catch.

FYI, Node-RED's http request node also seems to use try ~ catch on JSON.parse.
https://github.com/node-red/node-red/blob/master/nodes/core/io/21-httprequest.js#L160

**Comment by WarriorRocker** [comment]
Looks like this could affect the other nodes as well. Ideally someone would create a node package for interacting with the Seeed IoT API. I'm still relatively new to nodejs but I might take this on in the coming weeks. I haven't seen this error happen personally though it certainly makes sense, more thought needs to be given on handling error responses gracefully. Let me know if this keeps happening and I can patch them but for now if its a somewhat rare occurrence I'll probably defer this as part of over hauling the API functions themselves.

Thanks for catching these though, I have plans of using this package as part of a production system so it's great to have a log of bugs like this. Also it seems you're good at digging through the code which also helps a lot, feel free to try to fixing the code locally and submitting a pull request for it.

**Comment by WarriorRocker** [comment]
This should now be fixed, noticed this while running overnight. Also went ahead and put the change in for the other nodes as well so this shouldn't happen again. Let me know if it does.
